name: Test Secrets Configuration

on:
  workflow_dispatch: # Permite executar manualmente

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Test Supabase URL Secret
      run: |
        if [ -z "$VITE_SUPABASE_URL" ]; then
          echo "❌ VITE_SUPABASE_URL não está configurado ou está vazio"
          exit 1
        else
          echo "✅ VITE_SUPABASE_URL está configurado"
          echo "URL length: ${#VITE_SUPABASE_URL} caracteres"
          echo "URL starts with: ${VITE_SUPABASE_URL:0:20}..."
        fi
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        
    - name: Test Supabase Anon Key Secret
      run: |
        if [ -z "$VITE_SUPABASE_ANON_KEY" ]; then
          echo "❌ VITE_SUPABASE_ANON_KEY não está configurado ou está vazio"
          exit 1
        else
          echo "✅ VITE_SUPABASE_ANON_KEY está configurado"
          echo "Key length: ${#VITE_SUPABASE_ANON_KEY} caracteres"
          echo "Key starts with: ${VITE_SUPABASE_ANON_KEY:0:20}..."
        fi
      env:
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
    - name: Test Connection to Supabase
      run: |
        echo "🔗 Testando conexão com Supabase..."
        response=$(curl -s -o /dev/null -w "%{http_code}" "$VITE_SUPABASE_URL/rest/v1/" \
          -H "apikey: $VITE_SUPABASE_ANON_KEY" \
          -H "Authorization: Bearer $VITE_SUPABASE_ANON_KEY")
        
        if [ "$response" = "200" ]; then
          echo "✅ Conexão com Supabase OK (HTTP $response)"
        else
          echo "⚠️  Resposta HTTP: $response"
          echo "Isso pode ser normal dependendo da configuração do seu projeto"
        fi
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
    - name: Validate Secret Values
      run: |
        echo "🔍 Validando formato dos secrets..."
        
        # Validar URL do Supabase
        if [[ "$VITE_SUPABASE_URL" =~ ^https://[a-z0-9]+\.supabase\.co$ ]]; then
          echo "✅ Formato da URL Supabase está correto"
        else
          echo "❌ Formato da URL Supabase parece incorreto"
          echo "Esperado: https://[project-id].supabase.co"
        fi
        
        # Validar chave anônima (JWT format)
        if [[ "$VITE_SUPABASE_ANON_KEY" =~ ^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$ ]]; then
          echo "✅ Formato da chave anônima está correto (JWT)"
        else
          echo "❌ Formato da chave anônima parece incorreto"
          echo "Esperado: JWT format (eyJ...)"
        fi
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }} 